spring:
  application:
    name: monew-team08

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: info

backup:
  s3:
    bucket: ${AWS_S3_BUCKET}
    prefix: ${BACKUP_S3_STORAGE_PATH}

naver:
  api:
    client-id: ${NAVER_API_CLIENT_ID}
    client-secret: ${NAVER_API_CLIENT_SECRET}