spring:
  application:
    name: monew-team08

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    root: info
